<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-21T12:19:56 IST" name="Default suite" finished-at="2021-09-21T12:20:08 IST" duration-ms="11828">
    <groups>
    </groups>
    <test started-at="2021-09-21T12:19:56 IST" name="Default test" finished-at="2021-09-21T12:20:08 IST" duration-ms="11828">
      <class name="com.employeeapi.testcases.TC_GET_All_Employees">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.employeeapi.testcases.TC_GET_All_Employees@5d0a1059]" started-at="2021-09-21T12:19:56 IST" name="setup" finished-at="2021-09-21T12:19:56 IST" duration-ms="586" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="getAllemployes()[pri:0, instance:com.employeeapi.testcases.TC_GET_All_Employees@5d0a1059]" started-at="2021-09-21T12:19:56 IST" name="getAllemployes" finished-at="2021-09-21T12:20:07 IST" duration-ms="10906" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllemployes -->
        <test-method signature="chechStatusCode()[pri:0, instance:com.employeeapi.testcases.TC_GET_All_Employees@5d0a1059]" started-at="2021-09-21T12:20:07 IST" name="chechStatusCode" finished-at="2021-09-21T12:20:07 IST" duration-ms="24" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- chechStatusCode -->
        <test-method signature="checkContentType()[pri:0, instance:com.employeeapi.testcases.TC_GET_All_Employees@5d0a1059]" started-at="2021-09-21T12:20:07 IST" name="checkContentType" finished-at="2021-09-21T12:20:07 IST" duration-ms="10" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [text/html; charset=UTF-8] but found [application/json]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [text/html; charset=UTF-8] but found [application/json]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.employeeapi.testcases.TC_GET_All_Employees.checkContentType(TC_GET_All_Employees.java:87)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContentType -->
        <test-method signature="checkResponseBody()[pri:0, instance:com.employeeapi.testcases.TC_GET_All_Employees@5d0a1059]" started-at="2021-09-21T12:20:08 IST" name="checkResponseBody" finished-at="2021-09-21T12:20:08 IST" duration-ms="85" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseBody -->
        <test-method signature="checkResponseTime()[pri:0, instance:com.employeeapi.testcases.TC_GET_All_Employees@5d0a1059]" started-at="2021-09-21T12:20:08 IST" name="checkResponseTime" finished-at="2021-09-21T12:20:08 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseTime -->
        <test-method signature="checkStatusLine()[pri:0, instance:com.employeeapi.testcases.TC_GET_All_Employees@5d0a1059]" started-at="2021-09-21T12:20:08 IST" name="checkStatusLine" finished-at="2021-09-21T12:20:08 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusLine -->
      </class> <!-- com.employeeapi.testcases.TC_GET_All_Employees -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
